server:
    port: 4000
    error:
        include-message: always

spring:
    application:
        name: template-micro-service
    datasource:
        url: jdbc:postgresql://localhost:5432/gestion_ressources
        username: postgres
        password: 12345678
    jpa:
        hibernate:
            ddl-auto: update
        # show-sql : true
        # properties:
        #     hibernate:
        #         dialect: org.hibernate.dialect.PostgreSQLDialect
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 1024MB
            max-request-size: 1024MB


yowyob:
    openapi:
        prod-url: http://localhost:4000
        dev-url: http://localhost:4000
    
data:
    product-dir: /src/main/resources/image