server:
    port: 4000
    error:
        include-message: always

# debug: true

spring:
    application:
        name: template-micro-service
    cassandra:
        local-datacenter: datacenter1
        keyspace-name: gestion_ressources
        schema-action: recreate
        request.timeout: 10s
        connection.connect-timeout: 10s
        connection.init-query-timeout: 10s
        contact-points: 127.0.0.1
        
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 1024MB
            max-request-size: 1024MB


yowyob:
    openapi:
        prod-url: http://localhost:4000
        dev-url: http://localhost:4000
    
data:
    product-dir: /src/main/resources/image